package global_configs

const HEADERLENGTH = 6
const HASHLENGTH = 32
const STATUSCODEINDEX = 0
const OPERATIONCODEINDEX = 1
const REGISTERCOMPONENTOPERATIONCODE = 255
const GETCOMPONENTOPERATIONCODE = 254
const GETCOMPONENTSOPERATIONCODE = 253

// 0 REGISTER
// GET COMPONENT 1
// GET COMPONENTS 2
// SERVER OPERATION CODES
